import { PartItem, SavedVehicle } from "@/types";

export const MOCK_VEHICLE_MAKES = [
  { id: "honda", name: "Honda", type: "CAR" as const },
  { id: "yamaha", name: "Yamaha", type: "MOTORBIKE" as const },
  { id: "toyota", name: "Toyota", type: "CAR" as const },
  { id: "bmw", name: "BMW", type: "CAR" as const },
  { id: "kawasaki", name: "Kawasaki", type: "MOTORBIKE" as const },
  { id: "ferrari", name: "Ferrari", type: "CAR" as const },
  { id: "lamborghini", name: "Lamborghini", type: "CAR" as const },
  { id: "bugatti", name: "Bugatti", type: "CAR" as const },
  { id: "porsche", name: "Porsche", type: "CAR" as const },
  { id: "ducati", name: "Ducati", type: "MOTORBIKE" as const },
  { id: "bmw-motorrad", name: "BMW Motorrad", type: "MOTORBIKE" as const },
];

export const MOCK_VEHICLE_MODELS = [
  { id: "civic-fl5", makeId: "honda", name: "Civic Type R (FL5)", generation: "11th Gen FL5", startYear: 2022, endYear: 2026 },
  { id: "civic-fk8", makeId: "honda", name: "Civic Type R (FK8)", generation: "10th Gen FK8", startYear: 2017, endYear: 2021 },
  { id: "accord-cv3", makeId: "honda", name: "Accord 1.5T (CV3)", generation: "10th Gen", startYear: 2018, endYear: 2023 },
  { id: "yzf-r15", makeId: "yamaha", name: "YZF-R15 V3/V4", generation: "V3/V4", startYear: 2019, endYear: 2026 },
  { id: "pcx160", makeId: "honda", name: "PCX 160 ABS", generation: "JK05", startYear: 2021, endYear: 2026 },
  { id: "hilux-revo", makeId: "toyota", name: "Hilux Revo Rocco / GR Sport", generation: "AN120", startYear: 2020, endYear: 2026 },
  { id: "ferrari-488", makeId: "ferrari", name: "488", generation: "GTB", startYear: 2015, endYear: 2019 },
  { id: "lamborghini-huracan", makeId: "lamborghini", name: "Huracán", generation: "EVO", startYear: 2019, endYear: 2024 },
  { id: "bugatti-chiron", makeId: "bugatti", name: "Chiron", generation: "W16", startYear: 2016, endYear: 2024 },
  { id: "porsche-911", makeId: "porsche", name: "911 (992)", generation: "992", startYear: 2019, endYear: 2026 },
  { id: "ducati-panigale", makeId: "ducati", name: "Panigale", generation: "V4", startYear: 2018, endYear: 2026 },
  { id: "bmw-s1000rr", makeId: "bmw-motorrad", name: "S 1000 RR", generation: "K67", startYear: 2019, endYear: 2026 },
  { id: "kawasaki-ninja", makeId: "kawasaki", name: "Ninja", generation: "H2R", startYear: 2015, endYear: 2026 },
  { id: "yamaha-r1m", makeId: "yamaha", name: "YZF-R1M", generation: "Crossplane", startYear: 2015, endYear: 2026 },
];

export const MOCK_VEHICLE_TRIMS = [
  {
    id: "trim-fl5-20t",
    modelId: "civic-fl5",
    name: "2.0T VTEC Turbo Type R (315 HP)",
    engineCode: "K20C1",
    horsepower: 315,
    fuelType: "Petrol (95+ Octane)",
    fullDisplayName: "2023 Honda Civic Type R (FL5) 2.0T K20C1",
  },
  {
    id: "trim-fk8-20t",
    modelId: "civic-fk8",
    name: "2.0T VTEC Turbo Type R (306 HP)",
    engineCode: "K20C1",
    horsepower: 306,
    fuelType: "Petrol (95+ Octane)",
    fullDisplayName: "2019 Honda Civic Type R (FK8) 2.0T K20C1",
  },
  {
    id: "trim-accord-15t",
    modelId: "accord-cv3",
    name: "1.5T L15BE VTEC Turbo (190 HP)",
    engineCode: "L15BE",
    horsepower: 190,
    fuelType: "Petrol",
    fullDisplayName: "2021 Honda Accord (CV3) 1.5T VTEC",
  },
  {
    id: "trim-r15-v4",
    modelId: "yzf-r15",
    name: "155cc VVA Liquid Cooled (18.4 HP)",
    engineCode: "G3J5E",
    horsepower: 18.4,
    fuelType: "Petrol",
    fullDisplayName: "2023 Yamaha YZF-R15 V4 155cc VVA",
  },
  {
    id: "trim-pcx-160",
    modelId: "pcx160",
    name: "157cc eSP+ 4-Valve ABS (15.8 HP)",
    engineCode: "KF47E",
    horsepower: 15.8,
    fuelType: "Petrol",
    fullDisplayName: "2023 Honda PCX 160 eSP+ ABS",
  },
  {
    id: "trim-hilux-28gr",
    modelId: "hilux-revo",
    name: "2.8 GD Super Power Turbo Diesel GR Sport (224 HP)",
    engineCode: "1GD-FTV (High Output)",
    horsepower: 224,
    fuelType: "Diesel",
    fullDisplayName: "2024 Toyota Hilux Revo 2.8 GR Sport 4WD",
  },
  {
    id: "trim-ferrari-488",
    modelId: "ferrari-488",
    name: "GTB 3.9 V8 Twin Turbo",
    engineCode: "F154 CB",
    horsepower: 661,
    fuelType: "Petrol",
    fullDisplayName: "2018 Ferrari 488 GTB 3.9 V8 Twin Turbo",
  },
  {
    id: "trim-lamborghini-huracan",
    modelId: "lamborghini-huracan",
    name: "EVO 5.2 V10",
    engineCode: "5.2 L V10",
    horsepower: 631,
    fuelType: "Petrol",
    fullDisplayName: "2020 Lamborghini Huracán EVO 5.2 V10",
  },
  {
    id: "trim-bugatti-chiron",
    modelId: "bugatti-chiron",
    name: "8.0L W16 Quad-Turbo",
    engineCode: "W16",
    horsepower: 1479,
    fuelType: "Petrol",
    fullDisplayName: "2019 Bugatti Chiron 8.0L W16 Quad-Turbo",
  },
  {
    id: "trim-porsche-911",
    modelId: "porsche-911",
    name: "GT3 4.0L Flat-6",
    engineCode: "4.0 L Flat-6",
    horsepower: 503,
    fuelType: "Petrol",
    fullDisplayName: "2022 Porsche 911 (992) GT3 4.0L",
  },
  {
    id: "trim-ducati-panigale",
    modelId: "ducati-panigale",
    name: "V4 R",
    engineCode: "Desmosedici Stradale R",
    horsepower: 237,
    fuelType: "Petrol",
    fullDisplayName: "2023 Ducati Panigale V4 R",
  },
  {
    id: "trim-bmw-s1000rr",
    modelId: "bmw-s1000rr",
    name: "M 1000 RR",
    engineCode: "ShiftCam Inline-4",
    horsepower: 212,
    fuelType: "Petrol",
    fullDisplayName: "2023 BMW M 1000 RR",
  },
  {
    id: "trim-kawasaki-ninja",
    modelId: "kawasaki-ninja",
    name: "H2R 1000cc Supercharged",
    engineCode: "Supercharged Inline-4",
    horsepower: 310,
    fuelType: "Petrol",
    fullDisplayName: "2021 Kawasaki Ninja H2R",
  },
  {
    id: "trim-yamaha-r1m",
    modelId: "yamaha-r1m",
    name: "1000cc CP4",
    engineCode: "Crossplane Inline-4",
    horsepower: 200,
    fuelType: "Petrol",
    fullDisplayName: "2022 Yamaha YZF-R1M",
  },
];

export const MOCK_SAVED_VEHICLES: SavedVehicle[] = [
  {
    id: "garage-1",
    make: "Honda",
    model: "Civic Type R (FL5)",
    year: 2023,
    trim: "2.0T VTEC Turbo Type R (315 HP)",
    trimId: "trim-fl5-20t",
    nickname: "Track Day FL5",
    vin: "JHMFL5880PS001928",
    isDefault: true,
  },
  {
    id: "garage-2",
    make: "Yamaha",
    model: "YZF-R15 V3/V4",
    year: 2022,
    trim: "155cc VVA Liquid Cooled (18.4 HP)",
    trimId: "trim-r15-v4",
    nickname: "Daily Commuter R15",
    vin: "MLHYG0810N5099120",
    isDefault: false,
  },
  {
    id: "garage-3",
    make: "Toyota",
    model: "Hilux Revo Rocco / GR Sport",
    year: 2024,
    trim: "2.8 GD Super Power Turbo Diesel GR Sport (224 HP)",
    trimId: "trim-hilux-28gr",
    nickname: "Workhorse Revo",
    vin: "MROFR22G901882310",
    isDefault: false,
  },
];

export const MOCK_PARTS_CATALOG: PartItem[] = [
  {
    id: "part-1",
    sku: "HND-OF-003",
    oemPartNumber: "15400-RTA-003",
    title: "Honda Genuine OEM Engine Oil Filter Cartridge & O-Ring",
    brand: "Honda Genuine",
    category: "Engine & Drivetrain",
    grade: "OEM_GENUINE",
    price: 380,
    costPrice: 210,
    stockQuantity: 142,
    warehouseBin: "Bin A12",
    warehouseAisle: "Row 4",
    isUniversalFit: false,
    description: "Direct replacement OEM high-efficiency oil filter designed specifically for Honda K-Series, L-Series, and R-Series engines. Constructed with dual-stage synthetic blend filtration media to trap microscopic carbon debris and engine wear particles while maintaining optimal high-RPM oil pressure under track loads.",
    descriptionTh: "ไส้กรองน้ำมันเครื่องประสิทธิภาพสูงแท้ OEM ออกแบบมาเพื่อเครื่องยนต์ Honda ซีรีส์ K, ซีรีส์ L และซีรีส์ R โดยเฉพาะ ผลิตด้วยสื่อกรองใยสังเคราะห์สองชั้นเพื่อดักจับเศษคาร์บอนขนาดเล็กและอนุภาคการสึกหรอของเครื่องยนต์ ในขณะที่ยังคงรักษาแรงดันน้ำมันเครื่องที่รอบสูงให้เหมาะสมที่สุดภายใต้การใช้งานหนักในสนามแข่ง",
    specifications: {
      "Thread Size": "M20 x 1.5 mm",
      "Outer Diameter": "68 mm",
      "Height": "85 mm",
      "Filtration Efficiency": "99.2% @ 20 Microns",
      "Anti-Drainback Valve": "Silicone (High-Temp Rated)",
      "Bypass Valve Pressure": "14.5 PSI (1.0 Bar)",
      "Included Gaskets": "Pre-lubricated Nitrile O-Ring",
      "Warranty": "1 Year / 20,000 km Honda Manufacturer Warranty",
    },
    compatibilityList: [
      "2022-2026 Honda Civic Type R (FL5 2.0T K20C1)",
      "2017-2021 Honda Civic Type R (FK8 2.0T K20C1)",
      "2018-2023 Honda Accord (CV3 1.5T L15BE)",
      "2016-2021 Honda Civic 1.5T (FC/FK)",
      "2017-2023 Honda CR-V 1.5T & 2.4L",
    ],
    compatibleTrimIds: ["trim-fl5-20t", "trim-fk8-20t", "trim-accord-15t"],
    images: [
      {
        id: "img-1-1",
        imageUrl: "https://images.unsplash.com/photo-1635843105058-2514ffc84433?auto=format&fit=crop&w=1200&q=80",
        isPrimary: true,
        isExplodedDiagram: false,
      },
      {
        id: "img-1-2",
        imageUrl: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1200&q=80",
        isPrimary: false,
        isExplodedDiagram: false,
      },
      {
        id: "img-1-diagram",
        imageUrl: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80",
        isPrimary: false,
        isExplodedDiagram: true,
        callouts: [
          { calloutNumber: "#1", label: "Filter Outer Canister Body (Anodized Steel)", labelTh: "กระบอกกรองภายนอก (เหล็กเคลือบอโนไดซ์)", subPartSku: "15400-CAN-BODY", xCoord: 45, yCoord: 35, specs: "Heavy gauge stamped steel with burst rating over 300 PSI.", specsTh: "เหล็กปั๊มขึ้นรูปความหนาสูง ทนแรงดันจุดระเบิดได้มากกว่า 300 PSI" },
          { calloutNumber: "#2", label: "High-Temp Silicone O-Ring Base Gasket", labelTh: "ปะเก็นยางโอริงซิลิโคนทนความร้อนสูง", subPartSku: "91302-RTA-001", xCoord: 52, yCoord: 68, specs: "Pre-greased fluoro-elastomer sealing ring. Torque to 14 Nm.", specsTh: "แหวนซีลฟลูออโรอีลาสโตเมอร์เคลือบจาระบีล่วงหน้า ขันด้วยแรงบิด 14 นิวตันเมตร" },
          { calloutNumber: "#3", label: "Internal Spring-Loaded Bypass Valve", labelTh: "วาล์วระบายบายพาสแบบสปริงภายใน", subPartSku: "15400-BYPASS-VLV", xCoord: 38, yCoord: 52, specs: "Precision calibrated relief spring preventing oil starvation during cold morning starts.", specsTh: "สปริงระบายที่ปรับเทียบอย่างแม่นยำ ป้องกันภาวะขาดน้ำมันเครื่องระหว่างการสตาร์ทเครื่องยนต์ในตอนเช้าที่อากาศเย็น" },
        ],
      },
    ],
  },
  {
    id: "part-2",
    sku: "MTL-300V-5W30",
    oemPartNumber: "MOTUL-300V-4L",
    title: "Motul 300V Power 5W-30 ESTER Core® Synthetic Engine Oil (4 Liter Can)",
    brand: "Motul",
    category: "Engine & Drivetrain",
    grade: "PERFORMANCE",
    price: 3890,
    costPrice: 2800,
    stockQuantity: 68,
    warehouseBin: "Bin C04",
    warehouseAisle: "Row 1",
    isUniversalFit: true,
    description: "Motul 300V Power 5W-30 formulation using 100% Synthetic ESTER Core® Technology. Formulated exclusively for high-output turbocharged track builds and endurance racing. Delivers significant reduction in internal friction for up to +7.2 HP gain across the powerband while maintaining shear resistance at extreme oil temperatures over 140°C.",
    descriptionTh: "สูตร Motul 300V Power 5W-30 โดยใช้เทคโนโลยี Synthetic ESTER Core® 100% คิดค้นขึ้นมาโดยเฉพาะสำหรับรถแข่งเทอร์โบกำลังสูงและการแข่งรถแบบเอนดูแรนซ์ ช่วยลดแรงเสียดทานภายในได้อย่างมีนัยสำคัญเพื่อเพิ่มกำลังม้าได้สูงสุดถึง +7.2 HP ทั่วทั้งช่วงกำลัง ในขณะที่ยังคงทนทานต่อการตัดเฉือนที่อุณหภูมิน้ำมันสุดขั้วสูงกว่า 140°C",
    specifications: {
      "Viscosity Grade": "SAE 5W-30",
      "Base Oil Technology": "100% Synthetic ESTER Core®",
      "Volume": "4 Liters (Metal Can)",
      "High-Temp High-Shear (HTHS)": "3.6 mPa.s @ 150°C",
      "Pour Point": "-48°C",
      "Flash Point": "232°C",
      "Recommended Use": "Track Day / Time Attack / High-Output Street",
    },
    compatibilityList: [
      "Universal Fit across all Gasoline Turbocharged and Naturally Aspirated Engines",
      "Ideal for Honda Civic Type R (FL5/FK8), Accord 1.5T, BMW M2/M3, and Yamaha Superbikes",
    ],
    compatibleTrimIds: ["trim-fl5-20t", "trim-fk8-20t", "trim-accord-15t", "trim-r15-v4", "trim-pcx-160", "trim-hilux-28gr"],
    images: [
      {
        id: "img-2-1",
        imageUrl: "https://images.unsplash.com/photo-1596484552834-6a58f850e0a1?auto=format&fit=crop&w=1200&q=80",
        isPrimary: true,
        isExplodedDiagram: false,
      },
    ],
  },
  {
    id: "part-3",
    sku: "SPN-FL5-AERO-HD",
    oemPartNumber: "60100-FL5-000",
    title: "Spoon Sports Dry Carbon Fiber Vented Hood for FL5 Type R",
    brand: "Spoon Sports",
    category: "Body & Aero",
    grade: "PERFORMANCE",
    price: 84500,
    costPrice: 62000,
    stockQuantity: 4,
    warehouseBin: "Bin E01",
    warehouseAisle: "Aisle 8 (High-Value Locker)",
    isUniversalFit: false,
    description: "Authentic Spoon Sports Japan aerospace-grade autoclave dry carbon fiber hood designed specifically for the 11th-Gen Honda Civic Type R (FL5). Features dual NACA intake ducts directly feeding the factory airbox and massive central extraction louvers that lower under-hood engine temperatures by up to -18°C during high-speed hot laps.",
    descriptionTh: "ฝากระโปรงคาร์บอนไฟเบอร์เกรดอากาศยานแท้จาก Spoon Sports ประเทศญี่ปุ่น ออกแบบเฉพาะสำหรับ Honda Civic Type R (FL5) รุ่นที่ 11 โดดเด่นด้วยท่อดักอากาศ NACA คู่ที่ส่งอากาศเข้าสู่กล่องอากาศโรงงานโดยตรง และช่องระบายอากาศขนาดใหญ่ตรงกลางที่ช่วยลดอุณหภูมิเครื่องยนต์ใต้ฝากระโปรงลงสูงสุดถึง -18°C ระหว่างการขับขี่รอบความเร็วสูง",
    specifications: {
      "Material Composition": "Pre-preg 3K Twill Dry Carbon Fiber (Autoclave Cured)",
      "Finish": "Gloss UV-Resistant Polyurethane Clear Coat",
      "Weight": "6.8 kg (OEM Aluminum Hood: 13.2 kg — Saves -6.4 kg)",
      "Mounting Points": "Direct bolt-on utilizing factory hinges & OEM latch mechanism",
      "Rain Guard": "Includes removable inner water drainage channel tray",
      "Origin": "Made in Tokyo, Japan (Serial Numbered Authenticity Plate Included)",
    },
    compatibilityList: [
      "2022-2026 Honda Civic Type R (FL5 2.0T K20C1) Only",
    ],
    compatibleTrimIds: ["trim-fl5-20t"],
    images: [
      {
        id: "img-3-1",
        imageUrl: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1200&q=80",
        isPrimary: true,
        isExplodedDiagram: false,
      },
      {
        id: "img-3-diagram",
        imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
        isPrimary: false,
        isExplodedDiagram: true,
        callouts: [
          { calloutNumber: "#1", label: "NACA Air Box Duct Channel", labelTh: "ช่องดักอากาศ NACA Air Box", subPartSku: "SPN-DUCT-FL5", xCoord: 30, yCoord: 40, specs: "High velocity cold air ramp funneling cold ambient air straight to K20C1 intake filter.", specsTh: "ช่องนำอากาศเย็นความเร็วสูงเพื่อส่งอากาศเย็นรอบนอกตรงเข้าสู่กรองอากาศ K20C1" },
          { calloutNumber: "#2", label: "Central Heat Extraction Louvers", labelTh: "ช่องระบายความร้อนตรงกลาง", subPartSku: "SPN-LOUV-FL5", xCoord: 50, yCoord: 48, specs: "Aerodynamically shaped low-pressure zone vents drawing hot air off the turbo downpipe.", specsTh: "ช่องระบายอากาศโซนแรงดันต่ำที่มีรูปทรงตามหลักอากาศพลศาสตร์ ช่วยดึงลมร้อนออกจากท่อลดเทอร์โบ" },
          { calloutNumber: "#3", label: "OEM Latch Reinforcement Carbon Plate", labelTh: "แผ่นคาร์บอนเสริมความแข็งแรงสำหรับตัวล็อก OEM", subPartSku: "SPN-LATCH-PLT", xCoord: 50, yCoord: 85, specs: "Triple-reinforced structural carbon core ensuring safety at speeds exceeding 270 km/h.", specsTh: "แกนคาร์บอนโครงสร้างเสริมแรงสามชั้นเพื่อความปลอดภัยที่ความเร็วสูงกว่า 270 กม./ชม." },
        ],
      },
    ],
  },
  {
    id: "part-4",
    sku: "BRM-GT-FL5-RED",
    oemPartNumber: "1N1.9032A",
    title: "Brembo GT 6-Piston Monoblock Big Brake Kit (380x34mm Slotted Rotors)",
    brand: "Brembo",
    category: "Braking & Suspension",
    grade: "PERFORMANCE",
    price: 139000,
    costPrice: 105000,
    stockQuantity: 6,
    warehouseBin: "Bin D14",
    warehouseAisle: "Row 3",
    isUniversalFit: false,
    description: "The ultimate track brake upgrade for the FL5 and FK8 Civic Type R. Brembo GT series 6-piston forged aluminum monoblock calipers paired with 380mm 2-piece floating slotted directional rotors. Completely eliminates brake fade during intensive 30-minute track sessions while providing razor-sharp pedal modulation.",
    descriptionTh: "ชุดอัปเกรดเบรกระดับสุดยอดสำหรับ FL5 และ FK8 Civic Type R คาลิปเปอร์อะลูมิเนียมหล่อขึ้นรูป 6 ลูกสูบ Brembo GT ซีรีส์จับคู่กับจานเบรกทิศทางแบบเซาะร่อง 2 ชิ้นขนาด 380 มม. ขจัดปัญหาอาการเบรกเฟดระหว่างการขับขี่ในสนาม 30 นาทีได้อย่างสมบูรณ์ ในขณะที่ยังคงให้สัมผัสแป้นเบรกที่เฉียบคม",
    specifications: {
      "Caliper Construction": "Forged Aluminum Monoblock 6-Piston (Red Anodized with White Logo)",
      "Rotor Dimensions": "380 mm Diameter x 34 mm Thickness (Slotted Type 3 Vane Design)",
      "Rotor Hat": "Billet Aluminum Floating Bell (Anodized Gold)",
      "Included Brake Lines": "Goodridge Stainless Steel Braided PTFE Teflon Lines",
      "Included Pads": "Brembo High-Performance HP1000 Track/Street Hybrid Compound",
      "Minimum Wheel Clearance": "Requires 19-inch wheels with minimum +35 offset or spacer",
    },
    compatibilityList: [
      "2022-2026 Honda Civic Type R (FL5)",
      "2017-2021 Honda Civic Type R (FK8)",
    ],
    compatibleTrimIds: ["trim-fl5-20t", "trim-fk8-20t"],
    images: [
      {
        id: "img-4-1",
        imageUrl: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80",
        isPrimary: true,
        isExplodedDiagram: false,
      },
    ],
  },
  {
    id: "part-5",
    sku: "AKR-TITAN-FL5",
    oemPartNumber: "S-H2R2-HAPT",
    title: "Akrapovič Evolution Line Full Titanium Cat-Back Exhaust with Carbon Tips",
    brand: "Akrapovič",
    category: "Exhaust Systems",
    grade: "PERFORMANCE",
    price: 168000,
    costPrice: 129000,
    stockQuantity: 3,
    warehouseBin: "Bin B08",
    warehouseAisle: "Row 5",
    isUniversalFit: false,
    description: "Crafted in Slovenia from proprietary ultra-lightweight titanium alloys, the Akrapovič Evolution Line transforms the FL5 Type R's exhaust tone into an exotic, aggressive symphony. Features triple center exit carbon-fiber tailpipes with integrated active acoustic exhaust valves controlled via OEM drive mode switch.",
    descriptionTh: "สร้างสรรค์ขึ้นในสโลวีเนียจากโลหะผสมไทเทเนียมน้ำหนักเบาพิเศษสิทธิบัตรเฉพาะ Akrapovič Evolution Line เปลี่ยนเสียงท่อไอเสียของ FL5 Type R ให้เป็นซิมโฟนีที่ดุดันและแปลกใหม่ มาพร้อมปลายท่อคาร์บอนไฟเบอร์ออกกลางสามท่อและวาล์วเสียงท่อไอเสียแบบแอคทีฟที่ควบคุมผ่านสวิตช์โหมดการขับขี่ OEM",
    specifications: {
      "Material": "100% High-Grade Titanium (Exhaust Piping & Muffler Shells)",
      "Tailpipes": "Triple Center Exit Handcrafted Matte Dry Carbon Outer Sleeves",
      "Weight Reduction": "-8.2 kg compared to factory stainless steel system",
      "Power Gains": "+11.4 Horsepower @ 5,600 RPM / +14.2 Nm Torque @ 3,200 RPM",
      "Valve Control": "Plug & Play electronic actuator integrated with factory +R / Sport modes",
      "Homologation": "ECE / CARB compliant when run with OEM catalytic converter",
    },
    compatibilityList: [
      "2022-2026 Honda Civic Type R (FL5 2.0T K20C1) Direct Bolt-On",
    ],
    compatibleTrimIds: ["trim-fl5-20t"],
    images: [
      {
        id: "img-5-1",
        imageUrl: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1200&q=80",
        isPrimary: true,
        isExplodedDiagram: false,
      },
    ],
  },
  {
    id: "part-6",
    sku: "YAM-OIL-R15-V4",
    oemPartNumber: "5D7-E3440-00",
    title: "Yamaha Genuine OEM Engine Oil Filter Element for YZF-R15 & MT-15",
    brand: "Yamaha Genuine",
    category: "Engine & Drivetrain",
    grade: "OEM_GENUINE",
    price: 150,
    costPrice: 75,
    stockQuantity: 310,
    warehouseBin: "Bin A02",
    warehouseAisle: "Row 2",
    isUniversalFit: false,
    description: "Original Yamaha Genuine Parts (YGP) pleated paper cartridge oil filter designed for Yamaha 155cc VVA engines including YZF-R15 V3/V4, MT-15, XSR155, and Aerox 155. Ensures 100% factory flow rates and protects precision VVA variable valve actuators.",
    descriptionTh: "ไส้กรองน้ำมันเครื่องกระดาษจีบแท้ Yamaha (YGP) ออกแบบมาสำหรับเครื่องยนต์ Yamaha 155cc VVA ได้แก่ YZF-R15 V3/V4, MT-15, XSR155 และ Aerox 155 รับประกันอัตราการไหล 100% จากโรงงานและปกป้องระบบวาล์วแปรผัน VVA ที่แม่นยำ",
    specifications: {
      "Filter Element Type": "Pleated Cellulose Fiber Cartridge",
      "Height": "38 mm",
      "Outer Diameter": "38 mm",
      "Includes O-Ring": "Yes (Yamaha Part # 93210-54805)",
      "Recommended Interval": "Every 3,000 km or 6 months",
    },
    compatibilityList: [
      "2019-2026 Yamaha YZF-R15 V3 & V4 (155cc VVA)",
      "2019-2026 Yamaha MT-15 / XSR155",
      "2020-2026 Yamaha Aerox / NMAX 155",
    ],
    compatibleTrimIds: ["trim-r15-v4"],
    images: [
      {
        id: "img-6-1",
        imageUrl: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1200&q=80",
        isPrimary: true,
        isExplodedDiagram: false,
      },
    ],
  },
  {
    id: "part-7",
    sku: "TYT-OIL-HILUX-1GD",
    oemPartNumber: "90915-YZZD2",
    title: "Toyota Genuine OEM Spin-On Oil Filter for 1GD / 2GD Diesel Engines",
    brand: "Toyota Genuine",
    category: "Engine & Drivetrain",
    grade: "OEM_GENUINE",
    price: 290,
    costPrice: 160,
    stockQuantity: 420,
    warehouseBin: "Bin A18",
    warehouseAisle: "Row 4",
    isUniversalFit: false,
    description: "Official Toyota Genuine Parts spin-on oil filter engineered specifically for high-torque 2.8L 1GD-FTV and 2.4L 2GD-FTV common-rail turbo diesel engines found in Toyota Hilux Revo and Fortuner models.",
    descriptionTh: "ไส้กรองน้ำมันเครื่องแบบสปินออนแท้จาก Toyota ออกแบบมาเป็นพิเศษสำหรับเครื่องยนต์ดีเซลเทอร์โบคอมมอนเรลแรงบิดสูง 2.8L 1GD-FTV และ 2.4L 2GD-FTV ที่พบในรุ่น Toyota Hilux Revo และ Fortuner",
    specifications: {
      "Thread": "3/4-16 UNF",
      "Outer Diameter": "74 mm",
      "Filtration Media": "Dual-density resin impregnated synthetic paper",
      "Anti-Drainback": "Silicone formulation for rapid cold diesel starts",
      "Warranty": "Toyota Factory Genuine Guarantee",
    },
    compatibilityList: [
      "2015-2026 Toyota Hilux Revo (2.8L 1GD / 2.4L 2GD)",
      "2015-2026 Toyota Fortuner (2.8L / 2.4L Diesel)",
      "2015-2023 Toyota HiAce Commuter Diesel",
    ],
    compatibleTrimIds: ["trim-hilux-28gr"],
    images: [
      {
        id: "img-7-1",
        imageUrl: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=1200&q=80",
        isPrimary: true,
        isExplodedDiagram: false,
      },
    ],
  },
];

export const MOCK_ADMIN_ORDERS = [
  {
    id: "ORD-992",
    orderNumber: "ORD-20260723-00992",
    customerName: "Somchai K.",
    customerPhone: "081-928-3341",
    totalAmount: 4520.00,
    fulfillmentType: "EXPRESS_SHIPPING" as const,
    status: "VERIFYING_SLIP" as const,
    createdAt: "2026-07-23 14:15",
    paymentSlipUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=800&q=80",
    ocrVerifiedAmount: 4520.00,
    promptPayRef: "0149823901239",
    items: [
      { id: "item-1", partTitle: "Honda Genuine OEM Oil Filter (15400-RTA-003)", quantity: 1, unitPrice: 380, totalPrice: 380, vehicleName: "2023 Honda Civic Type R (FL5)" },
      { id: "item-2", partTitle: "Motul 300V Power 5W-30 Synthetic Oil (4L)", quantity: 1, unitPrice: 3890, totalPrice: 3890, vehicleName: "Universal Fit" },
    ],
    shippingFee: 250,
  },
  {
    id: "ORD-991",
    orderNumber: "ORD-20260723-00991",
    customerName: "Nattapong T.",
    customerPhone: "089-144-8890",
    totalAmount: 1250.00,
    fulfillmentType: "INSTORE_PICKUP" as const,
    status: "PREPARING_PARTS" as const,
    createdAt: "2026-07-23 13:40",
    paymentSlipUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=800&q=80",
    ocrVerifiedAmount: 1250.00,
    promptPayRef: "0149811200492",
    items: [
      { id: "item-3", partTitle: "Yamaha Genuine OEM Oil Filter Element", quantity: 2, unitPrice: 150, totalPrice: 300, vehicleName: "2023 Yamaha YZF-R15 V4" },
      { id: "item-4", partTitle: "Motul 300V Power 5W-30 Synthetic Oil (1L)", quantity: 1, unitPrice: 950, totalPrice: 950, vehicleName: "Universal Fit" },
    ],
    shippingFee: 0,
  },
  {
    id: "ORD-990",
    orderNumber: "ORD-20260723-00990",
    customerName: "Anan P.",
    customerPhone: "082-550-1123",
    totalAmount: 84500.00,
    fulfillmentType: "EXPRESS_SHIPPING" as const,
    status: "APPROVED" as const,
    createdAt: "2026-07-23 11:20",
    paymentSlipUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=800&q=80",
    ocrVerifiedAmount: 84500.00,
    promptPayRef: "0149798830112",
    items: [
      { id: "item-5", partTitle: "Spoon Sports Dry Carbon Fiber Vented Hood", quantity: 1, unitPrice: 84500, totalPrice: 84500, vehicleName: "2023 Honda Civic Type R (FL5)" },
    ],
    shippingFee: 0,
  },
];
